version: '3.9'

services:
  db:
    image: mongo
    restart: always
    volumes: 
      - 'dbdata:/data/db'
    container_name: basededatos  
  server:
    build: .
    restart: always
    ports:
      - '2000:2000'
    depends_on:
      - db    
    container_name: api
    links:
      - basededatos    
  frontend:
    build: ./cliente
    restart: always    
    ports:
      - '3000:3000'
    depends_on:
      - server    
    container_name: cliente
    links:
      - api                
volumes: 
  dbdata:       
  