version: '3.9'

services:
  db:
    image: mongo
    restart: always
    volumes: 
      - 'dbdata:/data/db'
  server:
    build: .
    restart: always
    ports:
      - '2000:2000'
    depends_on:
      - db    
    links:
      - db    
  frontend:
    build: ./cliente
    restart: always    
    ports:
      - '3000:3000'
    depends_on:
      - server    
    links:
      - server                
volumes: 
  dbdata:      